import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
    #"~/.config/alacritty/themes/themes/ashes_dark.toml"
]

[window]
opacity = 1

padding.x = 10
padding.y = 10

decorations = "None"

decorations_theme_variant = "Dark"

[font]
size = 11.0
offset = { x = 0, y = 5 }
builtin_box_drawing = true

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.italic]
family = "Hack Nerd Font"
style = "italic"
